spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shina_epr_db
    username: shina_epr_user
    password: f3300955#F123456
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

logging:
  level:
    uz.shinamagazin: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
